title = "CodeSpan"
description = "A beautiful diagnostics library, inspired by codespan-reporting for Rust"
gitRepoUrl = "https://github.com/VirtualButFake/codespan-lune"
gitSourceBranch = "master"
nestSections = true
baseUrl = "/codespan/"

[[vitepress.actions]]
text = "Guide"
href = "/codespan/docs/guide/intro"
content = '<svg class="-top-px ml-1 inline fill-current transition-transform duration-150 group-hover:translate-x-1" xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" > <path d="M13.025 1l-2.847 2.828 6.176 6.176h-16.354v3.992h16.354l-6.176 6.176 2.847 2.828 10.975-11z" /> </svg>'
class = "group mx-1.5 border border-indigo-600 bg-indigo-500 text-slate-100 hover:bg-indigo-600 dark:border-indigo-400 dark:hover:bg-indigo-400"
iconClass = "relative -top-px ml-1 inline fill-current transition-transform duration-150 group-hover:translate-x-1"

[[vitepress.actions]]
text = "API Reference"
href = "api_path"
class = "mx-1.5 border border-slate-400 bg-slate-300 text-slate-800 hover:bg-slate-400 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100 dark:hover:bg-slate-700"

[[vitepress.nav]]
text = "Home"
link = "/"

[[vitepress.nav]]
text = "Guide"
link = "/docs/guide/intro"
